
name: firebase_dart

repository: https://github.com/appsup-dart/firebase_dart


packages:
  - packages/**
ignore:
  - packages/**/example

ide:
  intellij: false

command:
  bootstrap:
    usePubspecOverrides: true
  version:
    includeScopes: true
    linkToCommits: true

scripts:
  preversion: 
    exec: dart test -j 1
    select-package:
      flutter: false
  version:
    exec: "$PWD/remove-prereleases-from-changelog.sh"


 