name: firebase_dart
description: A pure Dart implementation of the Firebase client
version: 0.7.10
author: Rik Bellens <rik.bellens@appsup.be>
homepage: https://github.com/appsup-dart/firebase_dart

environment:
  sdk: '>=1.14.0 <2.0.0'

dependencies:
  quiver: '>=0.22.0 <0.29.0'
  async: '>=1.13.0 <3.0.0'
  crypto: '>=2.0.1 <3.0.0'
  logging: '>=0.11.0 <0.12.0'
  frappe: '>=0.4.0 <0.5.0'
  convert: ^2.0.0
  sortedmap: '^0.4.1'
  web_socket_channel: '>=1.0.4 <2.0.0'
  isolate: '^1.1.0'
  collection: '^1.9.1'
  meta: '^1.1.5'

dev_dependencies:
  test: '>=0.12.0 <0.13.0'
