name: firebase_dart_flutter
description: A port of the Firebase database, auth and storage client to pure Dart code for use on flutter
version: 1.0.0-dev.2
homepage: https://github.com/appsup-dart/firebase_dart

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_dart: ^1.0.0-dev.23
  platform_info: ^2.2.0
  path_provider: ^1.6.27
  hive: ^1.4.4+1
  package_info: ^0.4.3+4
  google_sign_in: ^4.5.9
  google_sign_in_dartio: ^0.0.8
  flutter_facebook_auth: ^2.0.1
  sign_in_with_apple: ^2.5.4
  url_launcher: ^5.7.10

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: be.appsup.firebase_dart_flutter
        pluginClass: FirebaseDartFlutterPlugin
