name: firebase_dart_flutter
description: A new flutter plugin project.
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_dart:
    path: ../firebase_dart
  platform_info: ^2.2.0
  flutter_custom_tabs: ^0.6.0
  path_provider: ^1.6.27
  hive: ^1.4.4+1
  package_info: ^0.4.3+4

dev_dependencies:
  flutter_test:
    sdk: flutter
